name: mental_health_nlp
description: "A mental health check app with NLP."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Use stable SDK range instead of pre-release

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^2.7.0  # Downgraded to match earlier suggestions
  firebase_auth: ^4.2.8  # Downgraded for compatibility
  cloud_firestore: ^4.4.3  # Downgraded for compatibility
  http: ^1.3.0
  url_launcher: ^6.1.10  # Added for launching URLs
  flutter_tts: ^3.6.3  # Added for text-to-speech
  google_generative_ai: ^0.3.0  # For NLP (optional)
  provider: ^6.0.5  # For state management
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Downgraded to a stable version

flutter:
  uses-material-design: true
  assets:
    - assets/
  